### ISSUE TITLE
Unwanted behaviour when /cook command is used while another /cook command is running

### ISSUE THREAD

**Issue by Cocopyth** [Cocopyth/foodshare#5]
Because used data is not properly deleted, user data from the previous session is displayed. This could be a wanted behaviour (data is saved if user wants to do something else during the session and come back to it later but that would be messy).
I suggest cleaning completely user data in the `ask_for_meal` function (only when it follows the /cook command, not when it is a 'back'

**Comment by PierreGuilmin** [comment]
I agree, also when using the `/cook` command again while in a `/cook` conversation we should go back to the beginning and remove `user_data`.

**Comment by PierreGuilmin** [comment]
Is this fixed already?

**Comment by Cocopyth** [comment]
Well I fixed it the easiest way possible, lmk what you think.

Le jeu. 26 mars 2020 à 16:34, PierreGuilmin <notifications@github.com> a
écrit :
